services:
  web:
    build: .
    container_name: purandar-airport-web

    command: >
      gunicorn lmrs.wsgi:application
      --bind 127.0.0.1:8000
      --workers 4
      --threads 2
      --timeout 120

    env_file:
      - .env

    volumes:
      - /var/www/media/purandar-airport:/app/media

    network_mode: host

    restart: always