from django.urls import path
from . import views

urlpatterns = [
    path('', views.dashboard),
    path('tools/', views.tools),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('', views.home, name='home'),
    path('tools/inspection/', views.inspection_form),
    path('tools/inspection/', views.inspection_form, name='inspection_form'),
    path('tools/ready-reckoner/', views.ready_reckoner),
    path('api/ready-reckoner/exists/', views.check_ready_reckoner_village_exists, name='check_ready_reckoner_village_exists'),
    path('tools/ready-reckoner/list/', views.ready_reckoner_list, name='ready_reckoner_list'),
    path('tools/ready-reckoner/download-all/', views.download_all_ready_reckoner_csv, name='download_all_ready_reckoner_csv'),
    path('tools/ready-reckoner/edit/<int:id>/', views.edit_ready_reckoner, name='edit_ready_reckoner'),
    path('tools/ready-reckoner/delete/<int:id>/', views.delete_ready_reckoner, name='delete_ready_reckoner'),
    path('tools/ready-reckoner/delete-selected/', views.delete_selected_ready_reckoner, name='delete_selected_ready_reckoner'),
    path('tools/delete-document-attachment/<int:attachment_id>/', views.delete_document_attachment, name='delete_document_attachment'),
    path('tools/712/', views.land_record_712),
    path('tools/712/list/', views.land_record_712_list, name='land_record_712_list'),
    path('tools/712/download-all/', views.download_all_land_record_712_csv, name='download_all_land_record_712_csv'),
    path('tools/712/edit/<int:id>/', views.edit_land_record_712, name='edit_land_record_712'),
    path('tools/712/delete/<int:id>/', views.delete_land_record_712, name='delete_land_record_712'),
    path('tools/712/delete-selected/', views.delete_selected_land_record_712, name='delete_selected_land_record_712'),
    path('api/land-record-712/parse/', views.parse_land_record_712_html, name='parse_land_record_712_html'),
    path('api/land-record-712/preview/', views.land_record_712_preview_page, name='land_record_712_preview_page'),
    path('api/land-record-gut-numbers/', views.get_land_record_gut_numbers, name='land_record_gut_numbers'),
    path('api/land-record-owner-names/', views.get_land_record_owner_names, name='land_record_owner_names'),
    path('api/assessment-types/<str:village>/', views.get_assessment_types_by_village),
    path('api/years/<str:village>/<str:assessment_type>/', views.get_years_by_village_assessment),
    path('api/rates/<str:village>/<str:assessment_type>/', views.get_rates_by_village_assessment),
    path('api/project-stats/', views.get_project_stats, name='project_stats'),
    path('api/dashboard/affected-counts/', views.get_dashboard_affected_counts, name='dashboard_affected_counts'),
    path('dashboard/progress/', views.get_dashboard_progress, name='dashboard_progress'),
    path('api/layer-bounds/<str:layer_name>/', views.get_layer_bounds, name='layer_bounds'),
    path('api/location-data/', views.get_location_data), ## All location API Fetch Marathi from public to project
    path('api/gut-numbers/<str:village_name>/', views.get_gut_numbers_by_village, name='get_gut_numbers_by_village'),
    path('api/locations/', views.get_locations, name='get_locations'),
    path('inspections/', views.inspection_list, name='inspection_list'),
    path('inspection/edit/<int:id>/', views.edit_inspection, name='edit_inspection'),
    path('inspection/delete/<int:id>/', views.delete_inspection, name='delete_inspection'),
    path('inspections/download-all/', views.download_all_inspections_csv, name='download_all_inspections_csv'),
    path('api/tree-master/', views.get_tree_master_list, name='get_tree_master_list'),
    path('tools/asset-creation/', views.asset_creation, name='asset_creation'),
    path('api/asset-fields/<str:asset_code>/', views.get_asset_fields_by_type, name='get_asset_fields_by_type'),
    path('tools/documents/', views.doc_upload, name='doc_upload'),
    path('tools/documents/delete/<int:id>/', views.doc_delete, name='doc_delete'),
    path('tools/documents/edit/<int:id>/', views.doc_edit, name='doc_edit'),
    path('api/documents/', views.doc_list_api, name='doc_list_api'),
    path('api/filter-documents/', views.get_filtered_documents, name='filter_documents'),
    path('tools/asset-list/', views.asset_list, name='asset_list'),
    path('tools/asset-list/download-all/', views.download_all_assets_csv, name='download_all_assets_csv'),
    path('asset/edit/<int:id>/', views.edit_asset, name='edit_asset'),
    path('asset/delete/<int:id>/', views.delete_asset, name='delete_asset'),
    path('tools/village-info/form/', views.village_info_form, name='village_info_form'),
    path('tools/village-info/', views.village_info_list, name='village_info'),
    path('tools/add-entry/', views.add_entry, name='add_entry'),
    path('tools/process-chart-form/', views.process_chart_list, name='process_chart_form'),
    path('tools/process-chart-form/form/', views.process_chart_form, name='process_chart_form_entry'),
    path('tools/process-chart-form/delete/<int:id>/', views.delete_process_chart_case, name='delete_process_chart_case'),
    path('api/process-chart-form/data/', views.get_process_chart_form_data, name='process_chart_form_data'),
    path('api/process-chart-form/save/', views.save_process_chart_form, name='save_process_chart_form'),
    path('tools/add-entry/list/', views.entry_list, name='entry_list'),
    path('tools/add-entry/delete/<int:id>/', views.delete_entry, name='delete_entry'),
    path('tools/rate-calculator/', views.village_info_list, name='rate_calculator'),
    path('api/rr-rate-by-village/<str:village>/', views.get_rr_rate_by_village, name='rr_rate_by_village'),
    path('api/village-info/data/', views.get_village_info_data, name='village_info_data'),
    path('api/village-info/exists/', views.check_village_info_exists, name='check_village_info_exists'),
    path('api/village-info/list/', views.get_village_info_list, name='village_info_list'),
    path('api/village-info/sec15-rates/', views.get_village_sec15_rates, name='village_info_sec15_rates'),
    path('api/village-info/delete-file/<int:file_id>/', views.delete_village_file, name='delete_village_file'),
    path('api/village-info/delete-sec4-row-file/<int:file_id>/', views.delete_village_sec4_row_file, name='delete_village_sec4_row_file'),
    path('api/village-info/delete-sec8-row-file/<int:file_id>/', views.delete_village_sec8_row_file, name='delete_village_sec8_row_file'),
    path('api/village-info/delete-8a-file/<int:file_id>/', views.delete_village_8a_file, name='delete_village_8a_file'),
    path('api/village-info/delete/<int:record_id>/', views.delete_village_info_record, name='delete_village_info_record'),
]
