from django.urls import path
from . import views

urlpatterns = [
    path('', views.dashboard),
    path('tools/', views.tools),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    # path('tools/', views.tools, name='tools'),
    path('', views.home, name='home'),
    path('tools/inspection/', views.inspection_form),
    path('tools/inspection/', views.inspection_form, name='inspection_form'),
    path('tools/inspection/', views.inspection_form),
    path('tools/ready-reckoner/', views.ready_reckoner),
    path('tools/ready-reckoner/list/', views.ready_reckoner_list, name='ready_reckoner_list'),
    path('tools/ready-reckoner/edit/<int:id>/', views.edit_ready_reckoner, name='edit_ready_reckoner'),
    path('tools/ready-reckoner/delete/<int:id>/', views.delete_ready_reckoner, name='delete_ready_reckoner'),
    path('tools/712/', views.land_record_712),
    path('tools/712/list/', views.land_record_712_list, name='land_record_712_list'),
    path('tools/712/edit/<int:id>/', views.edit_land_record_712, name='edit_land_record_712'),
    path('tools/712/delete/<int:id>/', views.delete_land_record_712, name='delete_land_record_712'),
    path('api/assessment-types/<str:village>/', views.get_assessment_types_by_village),
    path('api/rates/<str:village>/<str:assessment_type>/', views.get_rates_by_village_assessment),
    path('api/villages-list/', views.get_villages_list, name='villages_list'),
    path('api/all-villages-compensation/', views.get_all_villages_compensation, name='all_villages_compensation'),
    path('api/all-villages-farmers/', views.get_all_villages_farmers, name='all_villages_farmers'),
    path('api/project-stats/', views.get_project_stats, name='project_stats'),
    path('api/gut-numbers/<str:village_name>/', views.get_gut_numbers_by_village, name='gut_numbers'),
    path('api/gut-stats/<str:village_name>/<str:gut_number>/', views.get_gut_stats, name='gut_stats'),
    path('api/layer-bounds/<str:layer_name>/', views.get_layer_bounds, name='layer_bounds'),
    path("api/location-data/", views.get_location_data),
    path("api/gut-numbers/<str:village>/", views.get_gut_numbers),
    #APIS to fetch location data and Gut numbers for dropdowns
    path("api/location-data/", views.get_location_data),
    path("api/gut-numbers/<str:village>/", views.get_gut_numbers),
    path('inspections/', views.inspection_list, name='inspection_list'),
    path('inspection/edit/<int:id>/', views.edit_inspection, name='edit_inspection'),
    path('inspection/delete/<int:id>/', views.delete_inspection, name='delete_inspection'),
    path('inspections/download-all/', views.download_all_inspections_csv, name='download_all_inspections_csv'),
]
