# Generated by Django 6.0.3 on 2026-03-20 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=100)),
                ('taluka', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('gut_number', models.CharField(max_length=50)),
                ('officer', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LandRecord712',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=100)),
                ('taluka', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=150)),
                ('gut_number', models.CharField(max_length=50)),
                ('date', models.DateField(blank=True, null=True)),
                ('assessment_type', models.CharField(blank=True, max_length=200, null=True)),
                ('aakarnee', models.CharField(blank=True, max_length=100, null=True)),
                ('rate_applied', models.CharField(blank=True, max_length=100, null=True)),
                ('rate_year', models.CharField(blank=True, max_length=20, null=True)),
                ('document_712', models.FileField(blank=True, null=True, upload_to='712_documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='land_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FarmerNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('land_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmers', to='app.landrecord712')),
            ],
        ),
        migrations.CreateModel(
            name='ReadyReckonerRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=100)),
                ('taluka', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('year', models.CharField(default='2024-2025', max_length=20)),
                ('assessment_type', models.CharField(max_length=200)),
                ('assessment_range_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('assessment_range_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=15)),
                ('unit', models.CharField(choices=[('हेक्टर', 'हेक्टर'), ('चौ. मीटर', 'चौ. मीटर')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rr_rates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TreeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('length', models.FloatField(blank=True, null=True)),
                ('width', models.FloatField(blank=True, null=True)),
                ('girth', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trees', to='app.inspection')),
            ],
        ),
    ]
