# Generated by Django 6.0.3 on 2026-03-18 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [

        migrations.CreateModel(
            name='LandRecord712',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=100)),
                ('taluka', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=150)),
                ('gut_number', models.CharField(max_length=50)),
                ('farmer_name', models.CharField(max_length=200)),
                ('assessment_type', models.CharField(blank=True, max_length=200, null=True)),
                ('aakarnee', models.CharField(blank=True, max_length=100, null=True)),
                ('rate_applied', models.CharField(blank=True, max_length=100, null=True)),
                ('document_712', models.FileField(blank=True, null=True, upload_to='712_documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReadyReckonerRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=100)),
                ('taluka', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('assessment_type', models.CharField(max_length=200)),
                ('assessment_range_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('assessment_range_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=15)),
                ('unit', models.CharField(choices=[('हेक्टर', 'हेक्टर'), ('चौ. मीटर', 'चौ. मीटर')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
