# Generated by Django 6.0.3 on 2026-03-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree_name_marathi', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'db_table': 'tree_master',
                'ordering': ['tree_name_marathi'],
            },
        ),
    ]
