# Generated by Django 6.0.3 on 2026-06-04 09:01

from django.db import migrations


def drop_process_chart_location_unique_constraints(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return

    table_name = 'app_processchartcase'
    target_columns = ['user_id', 'district', 'taluka', 'village', 'gut_number']
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT constraint_name
            FROM (
                SELECT
                    con.conname AS constraint_name,
                    array_agg(att.attname::text ORDER BY ord.ordinality) AS column_names
                FROM pg_constraint con
                JOIN pg_class rel ON rel.oid = con.conrelid
                JOIN unnest(con.conkey) WITH ORDINALITY AS ord(attnum, ordinality) ON TRUE
                JOIN pg_attribute att ON att.attrelid = rel.oid AND att.attnum = ord.attnum
                WHERE rel.relname = %s
                    AND con.contype = 'u'
                GROUP BY con.conname
            ) constraints
            WHERE column_names = %s::text[]
                OR constraint_name LIKE 'app_processchartcase_user_id_district_taluka%%_uniq'
            """,
            [table_name, target_columns],
        )
        constraint_names = [row[0] for row in cursor.fetchall()]
        for constraint_name in constraint_names:
            cursor.execute(
                f'ALTER TABLE {schema_editor.quote_name(table_name)} '
                f'DROP CONSTRAINT IF EXISTS {schema_editor.quote_name(constraint_name)}'
            )


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
    migrations.RunPython(
        drop_process_chart_location_unique_constraints,
        reverse_code=migrations.RunPython.noop,
    ),
    migrations.AlterUniqueTogether(
        name='processchartcase',
        unique_together=set(),
    ),
]
