# Generated by Django 6.0.3 on 2026-05-07 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessChartCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(max_length=100)),
                ('taluka', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=150)),
                ('gut_number', models.CharField(max_length=50)),
                ('project_purpose', models.CharField(blank=True, max_length=255, null=True)),
                ('acquisition_type', models.CharField(blank=True, max_length=100, null=True)),
                ('current_step', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('land_record_id_ref', models.BigIntegerField(blank=True, null=True)),
                ('rr_info_id_ref', models.BigIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_chart_cases', to=settings.AUTH_USER_MODEL)),
                ('village_data_id_ref', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('user', 'district', 'taluka', 'village', 'gut_number')},
            },
        ),
        migrations.CreateModel(
            name='ProcessChartDepartmentRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_type', models.CharField(choices=[('panipurvatha', 'पाणीपुरवठा'), ('krushi', 'कृषी विभाग'), ('bandhakam', 'बांधकाम विभाग'), ('van', 'वन विभाग'), ('itar', 'इतर विभाग')], max_length=30)),
                ('owner_name', models.CharField(blank=True, max_length=255, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('valuation', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('related_component_details', models.TextField(blank=True, null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_rows', to='app.processchartcase')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessChartDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_no', models.PositiveSmallIntegerField()),
                ('section_code', models.CharField(max_length=100)),
                ('document_type', models.CharField(max_length=100)),
                ('file', models.FileField(max_length=1000, upload_to='process_chart/files/')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='app.processchartcase')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessChartOwnerNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=255)),
                ('area', models.CharField(blank=True, max_length=50, null=True)),
                ('notice_type', models.CharField(choices=[('personal_notice', 'Personal Notice'), ('public_notice', 'Public Notice'), ('award_notice', 'Award Notice'), ('sample_6', 'Sample 6'), ('forced_notice', 'Forced Notice'), ('possession_notice', 'Possession Notice')], max_length=30)),
                ('notice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('notice_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_farmer_id_ref', models.BigIntegerField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_notices', to='app.processchartcase')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessChartValuationRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valuation_type', models.CharField(max_length=255)),
                ('assessment_range', models.CharField(blank=True, max_length=100, null=True)),
                ('value_division', models.CharField(blank=True, max_length=100, null=True)),
                ('ready_reckoner_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('committee_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuation_rows', to='app.processchartcase')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessChartStepData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_no', models.PositiveSmallIntegerField()),
                ('section_code', models.CharField(max_length=100)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_data', to='app.processchartcase')),
            ],
            options={
                'unique_together': {('case', 'step_no', 'section_code')},
            },
        ),
    ]
