# Generated by Django 6.0.3 on 2026-03-20 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='readyreckonerrate',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='ready_reckoner_documents/'),
        ),
    ]
