# Generated by Django 6.0.3 on 2026-03-18 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readyreckonerrate',
            name='unit',
            field=models.CharField(choices=[('हेक्टर', 'हेक्टर'), ('चौ. मीटर', 'चौ. मीटर')], max_length=50),
        ),
    ]
