# Generated by Django 6.0.3 on 2026-03-18 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_inspection_treedetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landrecord712',
            name='farmer_name',
        ),
        migrations.CreateModel(
            name='Farmer_Names',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('land_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmers', to='app.landrecord712')),
            ],
        ),
    ]
