# Generated by Django 6.0.3 on 2026-03-21 04:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_treemaster'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('building', 'इमारत'), ('wall', 'भिंत'), ('well', 'विहीर'), ('tree_asset', 'झाड / वनस्पती'), ('pipeline', 'पाईपलाईन'), ('road', 'रस्ता'), ('fencing', 'कंपाउंड / कुंपण')], max_length=100)),
                ('asset_name', models.CharField(max_length=255)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('taluka', models.CharField(blank=True, max_length=100, null=True)),
                ('village', models.CharField(blank=True, max_length=150, null=True)),
                ('gut_number', models.CharField(blank=True, max_length=100, null=True)),
                ('survey_date', models.DateField(blank=True, null=True)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('formula_text', models.TextField(blank=True, null=True)),
                ('total_measurement', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('final_calculation', models.TextField(blank=True, null=True)),
                ('final_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AssetMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('field_label', models.CharField(max_length=255)),
                ('field_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='app.asset')),
            ],
        ),
    ]
