# Generated by Django 6.0.3 on 2026-03-20 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_readyreckonerrate_document'),
        ('app', '0002_treemaster'),
    ]

    operations = [
    ]
