# Generated by Django 6.0.3 on 2026-03-18 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_readyreckonerrate_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='landrecord712',
            name='assessment_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
