# Generated by Django 6.0.3 on 2026-03-18 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_landrecord712_assessment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='landrecord712',
            name='document_712',
            field=models.FileField(blank=True, null=True, upload_to='712_documents/'),
        ),
    ]
