# Generated by Codex on 2026-06-18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_asset_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessChartAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_no', models.PositiveSmallIntegerField()),
                ('section_code', models.CharField(blank=True, default='', max_length=100)),
                ('field_path', models.CharField(max_length=255)),
                ('field_label', models.CharField(max_length=255)),
                ('old_value', models.TextField(blank=True, default='')),
                ('new_value', models.TextField(blank=True, default='')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='app.processchartcase')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_chart_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-changed_at', '-id'),
            },
        ),
    ]
