# Generated by Django 6.0.3 on 2026-03-21 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_asset_assetmeasurement'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetTypeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_code', models.CharField(max_length=100, unique=True)),
                ('asset_name_marathi', models.CharField(max_length=200)),
                ('asset_name_english', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'asset_type_master',
                'ordering': ['display_order', 'asset_name_marathi'],
            },
        ),
        migrations.CreateModel(
            name='AssetFieldMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('field_label_marathi', models.CharField(max_length=200)),
                ('field_label_english', models.CharField(blank=True, max_length=200, null=True)),
                ('field_type', models.CharField(choices=[('number', 'Number'), ('text', 'Text'), ('select', 'Select')], default='number', max_length=50)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('is_required', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='app.assettypemaster')),
            ],
            options={
                'db_table': 'asset_field_master',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
