# Generated by Django 6.0.3 on 2026-03-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_landrecord712_farmer_name_farmer_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='readyreckonerrate',
            name='year',
            field=models.CharField(default='2024-2025', max_length=20),
        ),
    ]
