# Generated by Django 6.0.3 on 2026-03-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_readyreckonerrate_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='landrecord712',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landrecord712',
            name='rate_year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
