# Generated by Django 6.0.3 on 2026-08-05 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_processchartauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='villagedata',
            name='sec6_rows',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='assetlist',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='processchartauditlog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
