# Generated by Django 6.0.3 on 2026-03-21 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_courtmatterdocument_generaldocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generaldocument',
            name='user',
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('general', 'General Document'), ('court', 'Court Matter Document')], max_length=20)),
                ('document_level', models.CharField(choices=[('district', 'District'), ('taluka', 'Taluka'), ('village', 'Village'), ('gut', 'Gut')], max_length=20)),
                ('district', models.CharField(max_length=100)),
                ('taluka', models.CharField(blank=True, max_length=100, null=True)),
                ('village', models.CharField(blank=True, max_length=150, null=True)),
                ('gut_number', models.CharField(blank=True, max_length=50, null=True)),
                ('document_name', models.CharField(max_length=255)),
                ('document', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('description', models.TextField(blank=True, null=True)),
                ('document_date', models.DateField(blank=True, null=True)),
                ('court_date', models.DateField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CourtMatterDocument',
        ),
        migrations.DeleteModel(
            name='GeneralDocument',
        ),
    ]
