# Generated by Django 6.0.3 on 2026-03-21 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_assettypemaster_assetfieldmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetFormulaMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula_label_marathi', models.CharField(max_length=255)),
                ('formula_label_english', models.CharField(blank=True, max_length=255, null=True)),
                ('formula_expression', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('asset_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='formula', to='app.assettypemaster')),
            ],
            options={
                'db_table': 'asset_formula_master',
            },
        ),
    ]
