# Generated by Django 6.0.3 on 2026-03-21 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_readyreckonerrate_document'),
        ('app', '0005_assetformulamaster'),
    ]

    operations = [
    ]
