# Generated by Django 6.0.3 on 2026-08-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_villagedata_sec6_rows_alter_assetcategory_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='villagedata',
            name='sec10_toggle',
            field=models.CharField(blank=True, default='nahi', max_length=10),
        ),
        migrations.AddField(
            model_name='villagedata',
            name='sec7_toggle',
            field=models.CharField(blank=True, default='nahi', max_length=10),
        ),
        migrations.AddField(
            model_name='villagedata',
            name='sec8_toggle',
            field=models.CharField(blank=True, default='nahi', max_length=10),
        ),
        migrations.AddField(
            model_name='villagedata',
            name='sec9_toggle',
            field=models.CharField(blank=True, default='nahi', max_length=10),
        ),
    ]
