# Generated by Django 6.0.3 on 2026-05-05 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_add_missing_landrecord712_columns_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentmaster',
            name='land_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.landrecord712'),
        ),
    ]
