# Generated by Django 6.0.3 on 2026-05-08 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_landrecord712_original_document_name'),
        ('app', '0006_sec8_newspaper_fields'),
    ]

    operations = [
    ]
