# Generated by Django 6.0.3 on 2026-03-21 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_generaldocument_user_document_and_more'),
        ('app', '0006_merge_20260321_1452'),
    ]

    operations = [
    ]
