# Generated by Django 4.2.11 on 2026-08-10 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_add_sec_toggle_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='processchartcase',
            name='is_record_authenticated',
            field=models.BooleanField(default=False),
        ),
    ]
