# Generated by Django 6.0.3 on 2026-03-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_merge_20260321_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmernames',
            name='potkharaba',
            field=models.CharField(blank=True, help_text='Format: H-R (e.g. 0-53)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='farmernames',
            name='total_area',
            field=models.CharField(blank=True, help_text='Format: H-R (e.g. 1-65)', max_length=20, null=True),
        ),
    ]
