# Generated by Django 4.2.11 on 2026-08-10 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_processchartcase_is_record_authenticated'),
    ]

    operations = [
        migrations.CreateModel(
            name='RorDistrict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('div_code', models.CharField(blank=True, max_length=20)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RorTaluka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talukas', to='app.rordistrict')),
            ],
            options={
                'ordering': ['district__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RorSurveyNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=150)),
                ('taluka', models.CharField(max_length=150)),
                ('village', models.CharField(max_length=180)),
                ('gut_number', models.CharField(max_length=50)),
                ('survey_number', models.CharField(max_length=100)),
                ('hissa_number', models.CharField(blank=True, max_length=80)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['gut_number', 'survey_number'],
                'indexes': [models.Index(fields=['district', 'taluka', 'village', 'gut_number'], name='app_ror_survey_loc_idx'), models.Index(fields=['survey_number'], name='app_ror_survey_no_idx')],
                'unique_together': {('district', 'taluka', 'village', 'gut_number', 'survey_number')},
            },
        ),
        migrations.CreateModel(
            name='RorDivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='app_ror_div_code_idx'), models.Index(fields=['name'], name='app_ror_div_name_idx')],
            },
        ),
        migrations.AddField(
            model_name='rordistrict',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='districts', to='app.rordivision'),
        ),
        migrations.CreateModel(
            name='RorVillage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=180)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('taluka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villages', to='app.rortaluka')),
            ],
            options={
                'ordering': ['taluka__district__name', 'taluka__name', 'name'],
                'indexes': [models.Index(fields=['code'], name='app_ror_vil_code_idx'), models.Index(fields=['name'], name='app_ror_vil_name_idx'), models.Index(fields=['taluka', 'name'], name='app_ror_vil_tn_idx')],
                'unique_together': {('taluka', 'code')},
            },
        ),
        migrations.AddIndex(
            model_name='rortaluka',
            index=models.Index(fields=['code'], name='app_ror_tal_code_idx'),
        ),
        migrations.AddIndex(
            model_name='rortaluka',
            index=models.Index(fields=['name'], name='app_ror_tal_name_idx'),
        ),
        migrations.AddIndex(
            model_name='rortaluka',
            index=models.Index(fields=['district', 'name'], name='app_ror_tal_dn_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rortaluka',
            unique_together={('district', 'code')},
        ),
        migrations.AddIndex(
            model_name='rordistrict',
            index=models.Index(fields=['div_code'], name='app_ror_dist_div_idx'),
        ),
        migrations.AddIndex(
            model_name='rordistrict',
            index=models.Index(fields=['code'], name='app_ror_dist_code_idx'),
        ),
        migrations.AddIndex(
            model_name='rordistrict',
            index=models.Index(fields=['name'], name='app_ror_dist_name_idx'),
        ),
    ]
