# Generated by Django 5.2.16 on 2026-08-11 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rordistrict_rortaluka_rorsurveynumber_rordivision_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationCommonInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by_user_id', models.PositiveBigIntegerField(default=1)),
                ('scope_type', models.CharField(choices=[('global', 'Global'), ('division', 'Division'), ('district', 'District')], db_index=True, default='global', max_length=20)),
                ('division_code', models.CharField(blank=True, db_index=True, max_length=20)),
                ('division_name', models.CharField(blank=True, max_length=150)),
                ('district_code', models.CharField(blank=True, db_index=True, max_length=20)),
                ('district_name', models.CharField(blank=True, max_length=150)),
                ('project_name', models.CharField(blank=True, max_length=255)),
                ('project_purpose', models.CharField(blank=True, max_length=255)),
                ('approval_no', models.CharField(blank=True, max_length=150)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('agency_name', models.CharField(blank=True, max_length=255)),
                ('special_project_name', models.CharField(blank=True, max_length=255)),
                ('officer1_name', models.CharField(blank=True, max_length=150)),
                ('officer1_post', models.CharField(blank=True, max_length=150)),
                ('officer2_name', models.CharField(blank=True, max_length=150)),
                ('officer2_post', models.CharField(blank=True, max_length=150)),
                ('officer3_name', models.CharField(blank=True, max_length=150)),
                ('officer3_post', models.CharField(blank=True, max_length=150)),
                ('officer3_email', models.EmailField(blank=True, max_length=254)),
                ('officer3_phone', models.CharField(blank=True, max_length=50)),
                ('officer3_order_file', models.FileField(blank=True, max_length=1000, upload_to='notification_common_info/')),
                ('officer3_order_original_name', models.CharField(blank=True, max_length=255)),
                ('officer4_name', models.CharField(blank=True, max_length=150)),
                ('officer4_post', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['scope_type', 'division_code'], name='notif_cpi_scope_div_idx'), models.Index(fields=['scope_type', 'district_code'], name='notif_cpi_scope_dist_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by_user_id', models.PositiveBigIntegerField(default=1)),
                ('district', models.CharField(max_length=100)),
                ('taluka', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('complete', 'Complete')], default='draft', max_length=20)),
                ('current_step', models.PositiveSmallIntegerField(default=1)),
                ('is_verified', models.BooleanField(default=False)),
                ('sections', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('common_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='app.notificationcommoninfo')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(max_length=160)),
                ('file', models.FileField(max_length=1000, upload_to='notification/')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='app.notification')),
            ],
            options={
                'ordering': ['field_key', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['district', 'taluka', 'village'], name='notif_location_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationfile',
            index=models.Index(fields=['field_key'], name='notif_file_field_idx'),
        ),
    ]
