# Generated by Django 6.0.3 on 2026-03-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_farmernames_potkharaba_farmernames_total_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='matter_type',
            field=models.CharField(blank=True, choices=[('arbitration', 'Arbitration'), ('civil_dispute', 'Civil Dispute')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='owner_name',
            field=models.CharField(blank=True, help_text='Name of land owner / farmer', max_length=200, null=True),
        ),
    ]
