# Generated by Django 6.0.3 on 2026-05-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_add_village_step1_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villagedata',
            name='sec14_approved_rate_details',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='villagedata',
            name='sec3_upvibhag_name',
            field=models.TextField(blank=True, default=''),
        ),
    ]
