# Generated by Django 6.0.3 on 2026-03-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_add_owner_name_matter_type_to_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolMaster',
            fields=[
                ('tool_id', models.AutoField(primary_key=True, serialize=False)),
                ('tool_name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tool_master',
                'ordering': ['display_order', 'tool_id'],
            },
        ),
    ]
