# Generated by Django 5.2.16 on 2026-08-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_notification_village_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='processchartcase',
            name='hissa_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
