# Generated by Django 6.0.3 on 2026-03-23 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_toolmaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='tool',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inspection_records', to='app.toolmaster'),
            preserve_default=False,
        ),
    ]
