# Generated by Django 6.0.3 on 2026-03-23 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_inspection_tool'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toolmaster',
            options={},
        ),
        migrations.RemoveField(
            model_name='toolmaster',
            name='display_order',
        ),
        migrations.AlterModelTable(
            name='toolmaster',
            table=None,
        ),
    ]
