# Generated by Django 6.0.3 on 2026-03-23 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_toolmaster_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='tool',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='asset_records', to='app.toolmaster'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='tool',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='document_records', to='app.toolmaster'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='landrecord712',
            name='tool',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='land_records', to='app.toolmaster'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='readyreckonerrate',
            name='tool',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rr_records', to='app.toolmaster'),
            preserve_default=False,
        ),
    ]
