# Generated by Django 6.0.3 on 2026-03-23 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_document_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='tool',
        ),
        migrations.RemoveField(
            model_name='document',
            name='tool',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='tool',
        ),
        migrations.RemoveField(
            model_name='landrecord712',
            name='tool',
        ),
        migrations.RemoveField(
            model_name='readyreckonerrate',
            name='tool',
        ),
    ]
