# Generated by Django 6.0.3 on 2026-03-24 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_asset_tool_remove_document_tool_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentmaster',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='documentmaster',
            name='document_type',
            field=models.CharField(choices=[('general', 'General Document'), ('court', 'Court Matter Document')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='documentmaster',
            name='matter_type',
            field=models.CharField(blank=True, choices=[('arbitration', 'Arbitration'), ('civil_dispute', 'Civil Dispute')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='documentmaster',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.toolmaster'),
        ),
        migrations.AlterField(
            model_name='documentmaster',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
