# Generated by Django 6.0.3 on 2026-03-26 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_documentmaster_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='government_estimated_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
