# Generated by Django 6.0.3 on 2026-03-26 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_asset_government_estimated_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='government_final_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
