# Generated by Django 6.0.3 on 2026-05-18 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_processchartcase_unique_without_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inspection',
            unique_together={('district', 'taluka', 'village', 'gut_number')},
        ),
    ]
