# Generated by Django 6.0.3 on 2026-05-19 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_processchartcase_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inspection',
            unique_together=set(),
        ),
    ]
